language: node_js
node_js: 17 # lts/* currently resolves to node 18 which doesn't work with ubuntu 16.04 xenial used by travis. try again later perhaps.
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
before_install: npm config set progress=false
stages:
  - test
jobs:
  include:
    - stage: test
      cache:
        directories:
          - ./node_modules
      install:
        - npm install
        - npm install codecov -g
      script:
        - npm run ci:build
        - npm run ci:test
        - npm run ci:reportCoverage
