language: node_js
# node_js: normally is "17" or "lts/*". disabling to let travis handle node version. manual version can cause OS incompatibilities.
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
before_install: npm config set progress=false
stages:
  - test
jobs:
  include:
    - stage: test
      cache:
        directories:
          - ./node_modules
      install:
        - npm install
        - npm install codecov -g
      script:
        - npm run ci:build
        - npm run ci:test
        - npm run ci:reportCoverage
