dist: jammy
language: node_js
node_js: 17 #  normally is "17" or "lts/*". removing it disabling has travis sometimes pick weird versions like 0.10.
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
before_install: npm config set progress=false
stages:
  - test
jobs:
  include:
    - stage: test
      cache:
        directories:
          - ./node_modules
      install:
        - npm install
        - npm install codecov -g
      script:
        - npm run ci:build
        - npm run ci:test
        - npm run ci:reportCoverage
