# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ngx-dynamic-hooks docs
description: >- # this means to ignore newlines until "baseurl:"
  The documentation for the ngx-dynamic-hooks library for Angular
domain: mtobisch.github.io                          # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://mtobisch.github.io/                    # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /ngx-dynamic-hooks/                        # place folder name if the site is served in a subfolder
github_username:  mtobisch

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end]
  syntax_highlighter_opts:
    default_lang: ts
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass

# Front matter defaults
defaults:
  - scope:
      path: "documentation" # Under which path prefix to set these defaults
      type: "pages"
    values:
      layout: "docs"
  - scope:
      path: "documentation"
    values:
      structure: "structure_v3"
  - scope:
      path: "documentation/v2"
    values:
      structure: "structure_v2"
      deprecated: true


# Exclude from processing to dist folder
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - node_modules
  - webpack.config.js
  - tsconfig.json
  - css
  - js
